### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by Cherry** [nodecraft/spawnpoint-nats#6]
Travis is currently used for CI, but we can switch to GitHub Actions.

Please see https://github.com/nodecraft/b2-cloud-storage/pull/14 for details on what needs to be included. (Code coverage can be ignored for now).

- Workflow test.yml - needs tweaks to support testing on more than just Linux
- Readme badge

**Comment by bLandais** [comment]
Can I try to do this one please ?

**Comment by Cherry** [comment]
Absolutely @bLandais, thanks for wanting to contribute!

Just submit a PR when you're ready and good luck on reaching your 4 PRs for Hacktoberfest!

PS. We have quite a few other repos that could use switching over too if you're interested in those; https://github.com/issues?q=is%3Aissue+org%3Anodecraft+label%3Ahacktoberfest+is%3Aopen

**Comment by Cherry** [comment]
Closed by #8
